### PR TITLE
Add TagOrUntagCustomer action schema

### PR DESCRIPTION
**Pull request by vova07**

### CODE REVIEW

**Comment by vova07** [comment]
please review

**Comment by XaosSintez** [comment]
Just wondering, is it possible to only add or only remove a tag?

**Comment by vova07** [comment]
@XaosSintez you can do both a the same time.
But first tags will be added and then removed.

**Comment by ashkarpetin** [comment]
@vova07 But `minItems: 1` means you should provide tags to add and to remove?

**Comment by XaosSintez** [comment]
No, i mean that both fields are required with `minItems: 1`. In this case you have to remove AND add tags. You can't only remove or only add a tag(s)

**Comment by vova07** [comment]
You are right guys.
I've adjusted the code.
Thank you!

**Comment by XaosSintez** [comment]
Thank you :-)
The last question - correct format for no tags (for example don't remove any tag) is an empty array or `null`?

**Comment by ashkarpetin** [comment]
There is no maxItems limit?

**Comment by XaosSintez** [comment]
@ashkarpetin i think i recall something like `maxItems: 1000` in API.

**Comment by vova07** [comment]
@XaosSintez the right format is an `empty` array. (But seems I need to add an adjustment to the code.)

@ashkarpetin added, thanks!

**Pull request merged**
