### PR TITLE
Add customer-merged global webhook event

### PR DESCRIPTION
**Pull request by 2e3s**
Also customer-created.

### CODE REVIEW

**Comment by vova07** [comment]
So we will not support this new event in rules engine?

**Comment by 2e3s** [comment]
@vova07 there has been no demand that (yet). Maybe we will later.

**Comment by 2e3s** [comment]
devs please review

**Comment by adamaltman** [comment]
It would be nice to have `customer-updated` too.

**Comment by 2e3s** [comment]
I'm not sure what payload to send with it. If only `customerId` as within the customer-created, then I can add easily.

**Comment by adamaltman** [comment]
I think so, but you should add to the _embedded the customer resource too.

**Comment by 2e3s** [comment]
devs please review

**Pull request merged**
